# -*- coding: utf-8 -*-
"""GroupAnalysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dstJIeX6URjRCfD22VgpWtQjGWOJ_JMS
"""

from google.colab import drive
drive.mount('/content/drive')

from joblib import dump, load

# Load the KMeans model
best_kmeans_model = load('/content/drive/MyDrive/Colab Notebooks/Social Network Mining/ModelCreation/best_kmeans_model.h5')
# Load the trained vectorizer
vectorizer = load('/content/drive/MyDrive/Colab Notebooks/Social Network Mining/ModelCreation/vectorizer.pkl')
# Load the LDA model
lda = load('/content/drive/MyDrive/Colab Notebooks/Social Network Mining/ModelCreation/lda.pkl')
# Load the Scaler model
scaler = load('/content/drive/MyDrive/Colab Notebooks/Social Network Mining/ModelCreation/scaler.pkl')

print("KMeans model loaded successfully")
print("Vectorizer model loaded successfully!")
print("LDA model loaded successfully!")
print("Scaler model loaded successfully!")

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans
from sklearn.decomposition import LatentDirichletAllocation
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.preprocessing import StandardScaler

"""# We now analyze the # groups that have been created for the different opinions of the data"""

def process_comments(comment):
    """
    Process and classify a comment into clusters using pre-trained/predefined models.
    """
    # Step 1: Preprocess text with CountVectorizer
    X = vectorizer.transform([comment])  # Use the pre-trained vectorizer

    # Step 2: Apply LDA for Topic Modeling
    topic_distributions = lda.transform(X)

    # Step 3: Normalize topic distributions
    topic_distributions_scaled = scaler.transform(topic_distributions)

    # Step 4: Use KMeans for clustering
    kmeans_labels = best_kmeans_model.predict(topic_distributions_scaled)

    return kmeans_labels[0]  # Return the cluster for this comment

def main():
    sample_comments = [
        # Cluster 0
        "Mary Peltola’s victory highlights a turning point for Indigenous representation in Congress.",
        "The extended Speaker of the House election reflects deep divisions within the Republican Party.",
        "Sarah Palin’s loss to Mary Peltola underscores the changing political dynamics in Alaska.",
        "The adoption of ranked-choice voting has shifted the electoral landscape in Alaska.",
        "Jim Jordan’s repeated bids for Speaker have exposed internal fractures within the GOP.",
        "Congress remains deadlocked as leadership disputes stall progress on key legislation.",
        "The grassroots efforts behind Peltola’s campaign serve as a model for underrepresented candidates.",
        "Alaska’s election results demonstrate the effectiveness of ranked-choice voting in competitive races.",
        "Republican leaders struggle to rally support behind a unified candidate for Speaker.",
        "Mary Peltola’s historic win marks the first Alaska Native to hold a seat in the U.S. House.",

        # Cluster 1
        "The Biden-Trump debate offered sharp contrasts on healthcare and economic recovery plans.",
        "Fact-checkers highlighted multiple inaccuracies during the heated presidential debate.",
        "Biden’s performance focused on unity, while Trump leaned into aggressive rhetoric.",
        "The second presidential debate will cover foreign policy and national security topics.",
        "Moderators faced challenges managing interruptions during the fiery exchanges.",
        "Polls after the debate show a tight race, with both candidates claiming victory.",
        "CNN’s analysis praised Biden’s composure under pressure during the debate.",
        "Viewers had mixed reactions to Trump’s aggressive style versus Biden’s calm approach.",
        "Debate fact-checking has become an essential tool for voters to discern truth from spin.",
        "The lack of a live audience during the debate gave it a unique, quieter tone.",

        # Cluster 2
        "The Democrats’ focus on healthcare and education could sway key swing states.",
        "Trump’s campaign strategy revolves around energizing his base in rural areas.",
        "The 2024 election hinges on voter turnout in battleground states.",
        "Biden’s climate change proposals have gained traction among younger voters.",
        "The Republican Party is emphasizing tax cuts as a cornerstone of their campaign.",
        "Independent voters are likely to play a decisive role in the upcoming election.",
        "The debates this year feel like a repeat of 2020, with few new ideas presented.",
        "Trump’s America First policies resonate with working-class voters in key regions.",
        "Biden’s outreach to moderate Republicans could tip the balance in tight districts.",
        "The Electoral College remains a controversial factor in determining the 2024 winner."
    ]



    for comment in sample_comments:
        X = vectorizer.transform([comment])
        topic_distributions = lda.transform(X)
        group = process_comments(comment)
        print(f"Comment: \"{comment}\"")
        print(f"Topic Distribution: {topic_distributions}")
        print(f"Group: {group}\n")

main()